### ISSUE TITLE
Web API Deployment 

### ISSUE THREAD

**Issue by donenrique24** [RNCan/BioSIM_Web_API_Prod#12]
Deployment at the development stage should be done on a physical server (ideally the same that hosts the Python version of the Web API). It should be checked whether the IIS express is good for production deployment. An installation procedure on the physical server should be created (packaging and registration as a service).

**Comment by jflavoie33** [comment]
Testing has shown that : 
1. IIS is the mandatory way to go to serve the app. When starting the app in standalone mode as a service, the server can access the application on itself, but the port is not exposed to other computers.
2. Configuration of IIS on Windows 10 has been successful, but only with manual deployment.  That means publishing from VS into a folder, then copying the folder to the IIS website folder.
3. FTP publishing seems to work, but the app doesn't start correctly on warm-up.  To be investigated.

**Comment by jflavoie33** [comment]
Final decided configuration is as follows:

IIS uses two sites (BioSIM_A and BioSIM_B) for web service hotswapping on ports 8081 and 8082
Windows port forwaring is used to forward port 8080 to either 8081 or 8082 depending on which site is live.
IIS has a third site named RootProxy rewriting URLs to redirect traffic incoming to ip.address/biosim/... to localhost port 8080.

Two batch files are used to update and hotswap the sites.  The batch files build, deploy, warmup and then swap the port forwarding rule to the new site.
