### ISSUE TITLE
Possible fail or lock when running in multiprocess mode

### ISSUE THREAD

**Issue by donenrique24** [RNCan/BioSIM_Web_API_Prod#23]
Some models fail at loading time or when the Execute method is called. This should be handled.

**Comment by donenrique24** [comment]
When failing at loading time, the whole server stops due to a FileLoadException, which is the anticipated behaviour. 
When failing at spawning time, the exception is caught and the new tasks do not replace the former ones. Normally all the tasks should fail.
When failing at execution time, this causes a lock. The process fails but the client waits indefinitely.

**Comment by jflavoie33** [comment]
Fixed as per 7dbb3ad4d6376dbe328d57f94a3124b67c9ead17
