### ISSUE TITLE
The IP address in the request logs is always that of the local host

### ISSUE THREAD

**Issue by donenrique24** [RNCan/BioSIM_Web_API_Prod#26]
This might be due to the rootproxy.

**Comment by donenrique24** [comment]
I've checked when I send a request directly on port 8081 and the logged IP address is that of the remote computer. It points to the proxy.

**Comment by jflavoie33** [comment]
Fixed as of commit 381e706fd24a5e1482c5ccab33a37c505ed7963b

To be able to use the X-Forwarded-for http header request used in reverse-proxies, we had to replace the app switching mechanism by two reverse-proxy sites bound to port 80 which we alternately enable.
