### ISSUE TITLE
Determine best azure instance type for this implementation

### ISSUE THREAD

**Issue by jflavoie33** [RNCan/BioSIM_Web_API_Prod#4]
This service implementation has been developed using a traditional approach, notably : 

- it uses multiple threads to distribute processing load on multiple cores even for a single request
- It uses a cache mechanism to allow faster processing of requests that share common characteristics with the latest requests

This suggests that it might be best using one or a few instances that would be more powerful (multiple cores, more RAM) than multiple standard web instances.

@donenrique24 @Tigroux any idea about the RAM requirements could be added here.

@swangcanada Would it be possible to use a higher tier instance for this project or would that require much changes to our current structure ?  Also, any relevant pricing information would be interesting for budgeting purposes.

**Comment by swangcanada** [comment]
Any idea how much bigger an instance you need? I do agree with you, in that this app requires its own instance

**Comment by jflavoie33** [comment]
Following the results in https://github.com/RNCan/BioSIM_Web_API_Prod/issues/6

It is mandatory to have a multiple core instance and testing has shown that a single instance in production mode (loading all databases and models) using three tasks takes 7GB of RAM.  This means that we can estimate RAM to 2.3GB per task.

The P3V2 instance has been tested and shows acceptable results.  
![image](https://user-images.githubusercontent.com/73243064/147672292-cf5f8df0-8850-427a-b23b-af3f53aebd9b.png)

The P2V3 instance should be tested as well 
![image](https://user-images.githubusercontent.com/73243064/147672330-9ffb2ce1-c2bb-4162-89b7-681c85201634.png)

With the pricing associated with those instance types, deploying on a standalone server is considered as well.

**Comment by donenrique24** [comment]
We wait for the Hub Team to put us in touch with the other Science Team which has access to more powerful instances. Once we get acceptable performance we can spot which instance best fit our needs and go see our managers with the price.

**Comment by jflavoie33** [comment]
Closing this issue for now, we can reopen when we get in touch with the other Science Team.
